# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/RecordSoundDialog.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_RecordSoundDialog(object):
    def setupUi(self, RecordSoundDialog):
        RecordSoundDialog.setObjectName("RecordSoundDialog")
        RecordSoundDialog.resize(676, 371)
        self.gridLayout = QtWidgets.QGridLayout(RecordSoundDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.graphicsView = PlotWidget(RecordSoundDialog)
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout.addWidget(self.graphicsView)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(RecordSoundDialog)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.doubleSpinBoxDuration = QtWidgets.QDoubleSpinBox(RecordSoundDialog)
        self.doubleSpinBoxDuration.setProperty("value", 2.0)
        self.doubleSpinBoxDuration.setObjectName("doubleSpinBoxDuration")
        self.horizontalLayout_3.addWidget(self.doubleSpinBoxDuration)
        self.label_3 = QtWidgets.QLabel(RecordSoundDialog)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.doubleSpinBoxFrequency = QtWidgets.QDoubleSpinBox(RecordSoundDialog)
        self.doubleSpinBoxFrequency.setDecimals(0)
        self.doubleSpinBoxFrequency.setMaximum(50000.0)
        self.doubleSpinBoxFrequency.setProperty("value", 48000.0)
        self.doubleSpinBoxFrequency.setObjectName("doubleSpinBoxFrequency")
        self.horizontalLayout_3.addWidget(self.doubleSpinBoxFrequency)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.pushButtonRecord = QtWidgets.QPushButton(RecordSoundDialog)
        self.pushButtonRecord.setObjectName("pushButtonRecord")
        self.horizontalLayout.addWidget(self.pushButtonRecord)
        self.pushButtonPlay = QtWidgets.QPushButton(RecordSoundDialog)
        self.pushButtonPlay.setObjectName("pushButtonPlay")
        self.horizontalLayout.addWidget(self.pushButtonPlay)
        self.pushButtonSave = QtWidgets.QPushButton(RecordSoundDialog)
        self.pushButtonSave.setObjectName("pushButtonSave")
        self.horizontalLayout.addWidget(self.pushButtonSave)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.LabelStatus = QtWidgets.QLabel(RecordSoundDialog)
        self.LabelStatus.setObjectName("LabelStatus")
        self.horizontalLayout_2.addWidget(self.LabelStatus)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(RecordSoundDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 1, 0, 1, 1)

        self.retranslateUi(RecordSoundDialog)
        self.buttonBox.accepted.connect(RecordSoundDialog.accept)
        self.buttonBox.rejected.connect(RecordSoundDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(RecordSoundDialog)

    def retranslateUi(self, RecordSoundDialog):
        _translate = QtCore.QCoreApplication.translate
        RecordSoundDialog.setWindowTitle(_translate("RecordSoundDialog", "Record Window"))
        self.label_2.setText(_translate("RecordSoundDialog", "Duration(Seconds)"))
        self.label_3.setText(_translate("RecordSoundDialog", "Frequency"))
        self.pushButtonRecord.setText(_translate("RecordSoundDialog", "Record"))
        self.pushButtonPlay.setText(_translate("RecordSoundDialog", "Play"))
        self.pushButtonSave.setText(_translate("RecordSoundDialog", "Save"))
        self.LabelStatus.setText(_translate("RecordSoundDialog", "Status"))

from pyqtgraph import PlotWidget
