# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/NewSinDialog.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_NewSinDialog(object):
    def setupUi(self, NewSinDialog):
        NewSinDialog.setObjectName("NewSinDialog")
        NewSinDialog.resize(402, 488)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(NewSinDialog.sizePolicy().hasHeightForWidth())
        NewSinDialog.setSizePolicy(sizePolicy)
        NewSinDialog.setMinimumSize(QtCore.QSize(402, 488))
        NewSinDialog.setMaximumSize(QtCore.QSize(402, 488))
        NewSinDialog.setSizeGripEnabled(False)
        self.buttonBox = QtWidgets.QDialogButtonBox(NewSinDialog)
        self.buttonBox.setGeometry(QtCore.QRect(180, 450, 221, 41))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.line = QtWidgets.QFrame(NewSinDialog)
        self.line.setGeometry(QtCore.QRect(0, 280, 401, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label = QtWidgets.QLabel(NewSinDialog)
        self.label.setGeometry(QtCore.QRect(0, 0, 411, 281))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("/Users/mikeldiez/Desktop/test2/pyqtgraph tests/assets/images/sinploted.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.widget = QtWidgets.QWidget(NewSinDialog)
        self.widget.setGeometry(QtCore.QRect(10, 300, 381, 151))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelAmplitude = QtWidgets.QLabel(self.widget)
        self.labelAmplitude.setObjectName("labelAmplitude")
        self.horizontalLayout.addWidget(self.labelAmplitude)
        self.doubleSpinBoxAmplitude = QtWidgets.QDoubleSpinBox(self.widget)
        self.doubleSpinBoxAmplitude.setMaximum(1.0)
        self.doubleSpinBoxAmplitude.setSingleStep(0.1)
        self.doubleSpinBoxAmplitude.setProperty("value", 1.0)
        self.doubleSpinBoxAmplitude.setObjectName("doubleSpinBoxAmplitude")
        self.horizontalLayout.addWidget(self.doubleSpinBoxAmplitude)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelFrequency = QtWidgets.QLabel(self.widget)
        self.labelFrequency.setObjectName("labelFrequency")
        self.horizontalLayout_2.addWidget(self.labelFrequency)
        self.doubleSpinBoxFrecuency = QtWidgets.QDoubleSpinBox(self.widget)
        self.doubleSpinBoxFrecuency.setMaximum(20000.0)
        self.doubleSpinBoxFrecuency.setProperty("value", 50.0)
        self.doubleSpinBoxFrecuency.setObjectName("doubleSpinBoxFrecuency")
        self.horizontalLayout_2.addWidget(self.doubleSpinBoxFrecuency)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.labelPhase = QtWidgets.QLabel(self.widget)
        self.labelPhase.setObjectName("labelPhase")
        self.horizontalLayout_3.addWidget(self.labelPhase)
        self.doubleSpinBoxPhase = QtWidgets.QDoubleSpinBox(self.widget)
        self.doubleSpinBoxPhase.setMaximum(1.0)
        self.doubleSpinBoxPhase.setObjectName("doubleSpinBoxPhase")
        self.horizontalLayout_3.addWidget(self.doubleSpinBoxPhase)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.widget1 = QtWidgets.QWidget(NewSinDialog)
        self.widget1.setGeometry(QtCore.QRect(11, 21, 41, 31))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.widget1)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.widget1)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.widget2 = QtWidgets.QWidget(NewSinDialog)
        self.widget2.setGeometry(QtCore.QRect(71, 21, 65, 31))
        self.widget2.setObjectName("widget2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget2)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.widget2)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.widget2)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.widget3 = QtWidgets.QWidget(NewSinDialog)
        self.widget3.setGeometry(QtCore.QRect(161, 11, 111, 41))
        self.widget3.setObjectName("widget3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget3)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_2 = QtWidgets.QLabel(self.widget3)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_6.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.widget3)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3)
        self.buttonBox.raise_()
        self.line.raise_()
        self.labelAmplitude.raise_()
        self.doubleSpinBoxAmplitude.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_6.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_7.raise_()

        self.retranslateUi(NewSinDialog)
        self.buttonBox.accepted.connect(NewSinDialog.accept)
        self.buttonBox.rejected.connect(NewSinDialog.reject)
        self.doubleSpinBoxFrecuency.valueChanged['double'].connect(self.label_3.setNum)
        self.doubleSpinBoxPhase.valueChanged['double'].connect(self.label_7.setNum)
        self.doubleSpinBoxAmplitude.valueChanged['double'].connect(self.label_5.setNum)
        QtCore.QMetaObject.connectSlotsByName(NewSinDialog)

    def retranslateUi(self, NewSinDialog):
        _translate = QtCore.QCoreApplication.translate
        NewSinDialog.setWindowTitle(_translate("NewSinDialog", "Pure Tone - Sin"))
        self.labelAmplitude.setText(_translate("NewSinDialog", "Amplitude (A)"))
        self.labelFrequency.setText(_translate("NewSinDialog", "Frequency (Fo)"))
        self.labelPhase.setText(_translate("NewSinDialog", "Phase (ϴ)"))
        self.label_6.setText(_translate("NewSinDialog", "ϴ="))
        self.label_7.setText(_translate("NewSinDialog", "1"))
        self.label_4.setText(_translate("NewSinDialog", "A="))
        self.label_5.setText(_translate("NewSinDialog", "1"))
        self.label_2.setText(_translate("NewSinDialog", "1/To=Fo="))
        self.label_3.setText(_translate("NewSinDialog", "50.00"))

